-- Inferred Celestial database structure.
-- Built from db.dbs.bak plus columns and tables referenced by the PHP code.
-- Prefer database/schema.sql generated by tools/export_schema.php for migration.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `seats`;
DROP TABLE IF EXISTS `caravan_vehicles`;
DROP TABLE IF EXISTS `caravans`;
DROP TABLE IF EXISTS `vehicles`;
DROP TABLE IF EXISTS `passengers`;
DROP TABLE IF EXISTS `role_alt`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `wards`;
DROP TABLE IF EXISTS `stakes`;
DROP TABLE IF EXISTS `destinations`;
DROP TABLE IF EXISTS `relationship`;
DROP TABLE IF EXISTS `documents`;
DROP TABLE IF EXISTS `sexs`;
DROP TABLE IF EXISTS `roles`;

CREATE TABLE `roles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `sexs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `slug` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `relationship` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `destinations` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `photo` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `stakes` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `cod` varchar(10) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_cod` (`cod`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `wards` (
  `id` varchar(36) NOT NULL,
  `id_stake` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `cod` varchar(10) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_cod` (`cod`),
  KEY `idx_id_stake` (`id_stake`),
  CONSTRAINT `wards_ibfk_1` FOREIGN KEY (`id_stake`) REFERENCES `stakes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `users` (
  `id` varchar(36) NOT NULL,
  `id_stake` varchar(36) DEFAULT NULL,
  `id_ward` varchar(36) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `salt` varchar(255) NOT NULL,
  `role` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `remember_token` varchar(32) DEFAULT NULL,
  `reset_token` varchar(32) DEFAULT NULL,
  `reset_token_expires` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_id_stake` (`id_stake`),
  KEY `idx_role` (`role`),
  KEY `idx_id_ward` (`id_ward`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`id_stake`) REFERENCES `stakes` (`id`),
  CONSTRAINT `users_ibfk_2` FOREIGN KEY (`role`) REFERENCES `roles` (`id`),
  CONSTRAINT `users_ibfk_3` FOREIGN KEY (`id_ward`) REFERENCES `wards` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `role_alt` (
  `id` varchar(36) NOT NULL,
  `role` int(11) NOT NULL,
  `stake_id` varchar(36) DEFAULT NULL,
  `ward_id` varchar(36) DEFAULT NULL,
  `expire_at` date NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_role_alt_role` (`role`),
  KEY `idx_role_alt_stake` (`stake_id`),
  KEY `idx_role_alt_ward` (`ward_id`),
  CONSTRAINT `role_alt_ibfk_1` FOREIGN KEY (`role`) REFERENCES `roles` (`id`),
  CONSTRAINT `role_alt_ibfk_2` FOREIGN KEY (`stake_id`) REFERENCES `stakes` (`id`),
  CONSTRAINT `role_alt_ibfk_3` FOREIGN KEY (`ward_id`) REFERENCES `wards` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `passengers` (
  `id` varchar(36) NOT NULL,
  `id_ward` varchar(36) NOT NULL,
  `id_church` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `nasc_date` date NOT NULL,
  `sex` int(11) NOT NULL,
  `id_document` int(11) NOT NULL,
  `document` varchar(255) NOT NULL,
  `obs` mediumtext DEFAULT NULL,
  `id_relationship` int(11) NOT NULL,
  `created_by` varchar(36) NOT NULL,
  `barcode` varchar(255) DEFAULT NULL,
  `expiration_date` date DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_id_document` (`id_document`),
  KEY `idx_sex` (`sex`),
  KEY `idx_user` (`created_by`),
  KEY `idx_ward` (`id_ward`),
  KEY `idx_relationship` (`id_relationship`),
  CONSTRAINT `passengers_ibfk_1` FOREIGN KEY (`id_document`) REFERENCES `documents` (`id`),
  CONSTRAINT `passengers_ibfk_2` FOREIGN KEY (`sex`) REFERENCES `sexs` (`id`),
  CONSTRAINT `passengers_ibfk_3` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `passengers_ibfk_4` FOREIGN KEY (`id_ward`) REFERENCES `wards` (`id`),
  CONSTRAINT `passengers_ibfk_5` FOREIGN KEY (`id_relationship`) REFERENCES `relationship` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `vehicles` (
  `id` varchar(36) NOT NULL,
  `id_stake` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `obs` text DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `capacity` int(11) DEFAULT NULL,
  `seat_map` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_id_stake` (`id_stake`),
  CONSTRAINT `vehicles_ibfk_1` FOREIGN KEY (`id_stake`) REFERENCES `stakes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `caravans` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `start_date` date NOT NULL,
  `start_time` time NOT NULL,
  `return_date` date NOT NULL,
  `return_time` time NOT NULL,
  `obs` text DEFAULT NULL,
  `id_stake` varchar(36) NOT NULL,
  `destination` varchar(36) DEFAULT NULL,
  `total_seats` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_caravans_id_stake` (`id_stake`),
  KEY `idx_caravans_destination` (`destination`),
  CONSTRAINT `caravans_ibfk_1` FOREIGN KEY (`id_stake`) REFERENCES `stakes` (`id`),
  CONSTRAINT `caravans_ibfk_2` FOREIGN KEY (`destination`) REFERENCES `destinations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `caravan_vehicles` (
  `id` varchar(36) NOT NULL,
  `id_caravan` varchar(36) NOT NULL,
  `id_vehicle` varchar(36) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `caravan_id` (`id_caravan`),
  KEY `vehicle_id` (`id_vehicle`),
  CONSTRAINT `caravan_vehicles_ibfk_1` FOREIGN KEY (`id_caravan`) REFERENCES `caravans` (`id`) ON DELETE CASCADE,
  CONSTRAINT `caravan_vehicles_ibfk_2` FOREIGN KEY (`id_vehicle`) REFERENCES `vehicles` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `seats` (
  `id` varchar(36) NOT NULL,
  `id_caravan_vehicle` varchar(36) DEFAULT NULL,
  `id_caravan` varchar(36) NOT NULL,
  `id_passenger` varchar(36) NOT NULL,
  `created_by` varchar(36) NOT NULL,
  `seat` varchar(255) DEFAULT NULL,
  `no_seat` tinyint(1) NOT NULL DEFAULT 0,
  `is_approved` tinyint(1) NOT NULL DEFAULT 0,
  `is_payed` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_id_caravan` (`id_caravan`),
  KEY `idx_id_caravan_vehicle` (`id_caravan_vehicle`),
  KEY `idx_id_passenger` (`id_passenger`),
  KEY `idx_created_by` (`created_by`),
  CONSTRAINT `seats_ibfk_1` FOREIGN KEY (`id_caravan_vehicle`) REFERENCES `caravan_vehicles` (`id`),
  CONSTRAINT `seats_ibfk_2` FOREIGN KEY (`id_caravan`) REFERENCES `caravans` (`id`),
  CONSTRAINT `seats_ibfk_3` FOREIGN KEY (`id_passenger`) REFERENCES `passengers` (`id`),
  CONSTRAINT `seats_ibfk_4` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
